// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGiOkunO-C_GA-PkvzaX-8nQfZY85UUAY',
    appId: '1:876442856362:web:6f8fc1e64c74da747959d3',
    messagingSenderId: '876442856362',
    projectId: 'parkcheck-app',
    authDomain: 'parkcheck-app.firebaseapp.com',
    storageBucket: 'parkcheck-app.firebasestorage.app',
    measurementId: 'G-582LM4TQNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzcxdLPQU2VMv3I_lSPHgw-O0PG7G6REg',
    appId: '1:876442856362:android:812165d8c701a57e7959d3',
    messagingSenderId: '876442856362',
    projectId: 'parkcheck-app',
    storageBucket: 'parkcheck-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2vR4xfAspoA-Z31CexsavQc9ZB3CRS7I',
    appId: '1:876442856362:ios:e8565348958763ea7959d3',
    messagingSenderId: '876442856362',
    projectId: 'parkcheck-app',
    storageBucket: 'parkcheck-app.firebasestorage.app',
    iosBundleId: 'com.example.parkcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2vR4xfAspoA-Z31CexsavQc9ZB3CRS7I',
    appId: '1:876442856362:ios:e8565348958763ea7959d3',
    messagingSenderId: '876442856362',
    projectId: 'parkcheck-app',
    storageBucket: 'parkcheck-app.firebasestorage.app',
    iosBundleId: 'com.example.parkcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGiOkunO-C_GA-PkvzaX-8nQfZY85UUAY',
    appId: '1:876442856362:web:a46d51c2e3938a027959d3',
    messagingSenderId: '876442856362',
    projectId: 'parkcheck-app',
    authDomain: 'parkcheck-app.firebaseapp.com',
    storageBucket: 'parkcheck-app.firebasestorage.app',
    measurementId: 'G-3LGMKVBN7D',
  );
}
